parameters:
    code_lovers_logging.monlog.handler.prowl.class: CodeLovers\LoggingBundle\Monolog\ProwlHandler
    code_lovers_logging.monlog.handler.jabber.class: CodeLovers\LoggingBundle\Monolog\JabberHandler

services:
    code_lovers_logging.prowl.connector:
        class: Prowl\Connector
        public: false

    code_lovers_logging.monlog.handler.prowl:
        class: %code_lovers_logging.monlog.handler.prowl.class%
        arguments: [@code_lovers_logging.prowl.connector]

    code_lovers_logging.monlog.handler.jabber:
        class: %code_lovers_logging.monlog.handler.jabber.class%
